# Generated by Django 2.2.5 on 2019-09-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190930_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default=models.CharField(max_length=30), max_length=30),
        ),
    ]
