# Generated by Django 2.2.5 on 2019-09-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190930_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontuple',
            name='tuple_name',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
