# Generated by Django 2.2.5 on 2019-09-30 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_questiontuple_tuple_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontuple',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='tuple',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='polls.QuestionTuple'),
            preserve_default=False,
        ),
    ]
